spring:
  datasource:
    url: jdbc:postgresql://194.233.87.193:5432/postgres
    #url: jdbc:postgresql://localhost:5432/db-development
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970 # ===Spring-Boot-API-Security-JWT===
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
  upload:
    client:
      path: C:\Users\V.I.P/Downloads/uploads/
    server:
      path: /home/sochoeun/uploads/

# openapi 3
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

